---
sidebar: sidebar 
permalink: scpivs44_remove_plugin.html 
keywords:  
summary: SnapCenterのデータ保護機能を使用する必要がなくなった場合は、SnapCenter VMwareプラグインを無効にしてvCenterから登録を解除してから、vCenterからSnapCenter VMwareプラグインを削除してから、残りのファイルを手動で削除する必要があります。 
---
= SnapCenter Plug-in for VMware vSphereの削除
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenterのデータ保護機能を使用する必要がなくなった場合は、SnapCenter VMwareプラグインを無効にしてvCenterから登録を解除してから、vCenterからSnapCenter VMwareプラグインを削除してから、残りのファイルを手動で削除する必要があります。

.開始する前に
* 管理者権限が必要です。
* 実行中のSnapCenterジョブがないことを確認します。


.手順
. の形式を使用して、SnapCenter VMwareプラグインの管理GUIにログインし `\https://<OVA-IP-address>:8080`ます。
+
プラグインを導入すると、SnapCenter VMwareプラグインのIPが表示されます。

. 左側のナビゲーションペインで * Configuration * をクリックし、次に * Plug-in Details * セクションの Service オプションの選択を解除してプラグインを無効にします。
. VMware vSphereにログインします。
. 左側のナビゲーション画面で、SnapCenter VMwareプラグインのインスタンス（仮想アプライアンスの導入時に使用されたファイルの名前）を右クリックし `.tar` 、*[ディスクから削除]*を選択します。
. SnapCenter VMwareプラグインを使用してアプリケーションと整合性のあるバックアップ用に他のSnapCenterプラグインをサポートしていた場合は、SnapCenterにログインしてvSphereホストを削除します。


.終了後
仮想アプライアンスはまだ導入されていますが、SnapCenter VMwareプラグインは削除されています。

SnapCenter VMwareプラグインのホストVMを削除したあと、ローカルのvCenterキャッシュが更新されるまでプラグインがvCenterに表示されたままになることがあります。ただし、プラグインが削除されたため、そのホストでSnapCenter VMware vSphereの処理を実行できません。ローカルvCenterキャッシュを更新する場合は、最初にSnapCenter VMwareプラグインの[Configuration]ページでアプライアンスが無効な状態になっていることを確認してから、vCenter Web Client Serviceを再起動します。
