---
sidebar: sidebar 
permalink: scpivs44_migration_overview.html 
keywords:  
summary:  
---
= 移行の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
migrationコマンドは、# SnapCenter 4.0以降の#からのみメタデータを移行します。以前のバージョンのSnapCenterを使用している場合は、移行前にアップグレードする必要があります。

* 移行対象に含まれるもの
+
** 移行される内容
+
SnapCenterメタデータ。ストレージシステム、カスタマイズしたスロットル、SnapCenter構成ファイルのEメール設定、ポリシー、リソースグループ、バックアップメタデータ、マウントが含まれます。（プリスクリプトまたはポストスクリプトが検出されると移行が失敗する）

** 移行されないもの
+
リソースグループ用に設定されたプリスクリプトとポストスクリプト

+
アクティブなゲストファイルのリストアセッション、ゲストファイルのリストアクレデンシャル、プロキシVM

+
ゲストファイルリストアセッションがアクティブなときに移行を開始すると、セッションは削除され、接続されたディスクはアンマウントされません。接続されているディスクを手動で削除しなければならない場合があります。

+
`scbr.override` 構成ファイル



* SnapCenterホストが中断されている
+
移行を確実に成功させるために、migrationコマンドはSnapCenterに登録されているすべてのホストを一時停止します。移行プロセスが正常に終了すると、SnapCenterホストが再開されます。

* 移行用コマンドレットのプロセス
+
SnapCenterに登録されているSnapCenter VMwareプラグインのインスタンスごとに、Windows PowerShellコマンドレットを使用する必要があります `invoke-SCVOVAMigration` 。

+
このコマンドレットは次の処理を実行します。

+
** 移行中にジョブが失敗しないように、すべてのスケジュールを一時停止します。移行が正常に完了すると、スケジュールは自動的に再度有効になります。
** ストレージ接続とメタデータを移行します。
** 移行後のバックアップのバックアップスケジュールを作成します。
** Windowsホストから既存のSnapCenter Plug-in for VMware vSphereをアンインストールします。
+
SnapCenter VMwareプラグインがSnapCenter Serverホストにインストールされていて、SnapCenterリポジトリ用に保護が設定されている場合は、SnapCenter Plug-in for VMware vSphereとSnapCenter Plug-in for Windowsを含むWindowsベースのプラグインパッケージも移行プロセスによってアンインストールされます。 その後、リポジトリ保護をサポートするために最新バージョンのSnapCenter Plug-in for Windowsを再インストールします。SnapCenter GUIのホストタイプが「vsphere」から「windows」に変わります。

** Windows SnapCenterサーバからvSphereホストとリソースグループを削除します。
** LinuxベースのSnapCenter VMwareプラグインでバックアップジョブをアクティブにします。
** 仮想化されたデータベースおよびファイル・システム（ VMDK バックアップを介したアプリケーション・ベースのバックアップ）をサポートするために、 SnapCenter VMware プラグイン用の vSphere ホストを SnapCenter に登録します。


* メタデータの格納先
+
アプリケーションベースのVMDKバックアップのメタデータは、SnapCenterサーバリポジトリに格納されます。VMとデータストアのバックアップのメタデータは、SnapCenter VMwareプラグインのMySQLリポジトリに格納されます。


