---
sidebar: sidebar 
permalink: scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere_01.html 
keywords:  
summary:  
---
= SnapCenter Plug-in for VMware vSphereの導入
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenterの機能を使用して仮想マシン上のVM、データストア、アプリケーションと整合性のあるデータベースを保護するには、SnapCenter Plug-in for VMware vSphereを導入する必要があります。ページには、 link:scpivs44_download_the_ova_open_virtual_appliance.html["Open Virtual Appliance（OVA；オープン仮想アプライアンス）のダウンロード"^] OVAファイルをダウンロードする手順が記載されています。

. VMware vCenter 7.0.3以降のバージョンの場合は、の手順に従って、 link:scpivs44_download_the_ova_open_virtual_appliance.html["Open Virtual Appliance（OVA；オープン仮想アプライアンス）のダウンロード"^] 証明書をvCenterにインポートします。
. ブラウザで、VMware vSphere vCenterに移動します。
+

NOTE: IPv6 HTML Webクライアントの場合は、ChromeまたはFirefoxを使用する必要があります。

. VMware vCenter Single Sign-Onページにログインします。
. ナビゲーションペインで、データセンター、フォルダ、クラスタ、ホストなどの仮想マシンの有効な親オブジェクトであるインベントリオブジェクトを右クリックし、[OVFテンプレートの展開*]を選択してVMware導入ウィザードを開始します。
. [Select an OVF template*（OVFテンプレートの選択）]ページで、ファイルの場所（次の表を参照）を指定し `.ova` 、*[Next]*をクリックします。
+
|===
| このウィザードのページ | 操作 


| 名前とフォルダを選択 | VMまたはvAppの一意の名前を入力し、導入先を選択します。 


| リソースを選択 | 導入したVMテンプレートを実行するリソースを選択します。 


| 詳細の確認 | テンプレートの詳細を確認します `.ova` 。 


| 使用許諾契約書 | [I accept all license agreements * ] のチェックボックスをオンにします。 


| ストレージの選択 | 導入したOVFテンプレートのファイルの保存場所と保存方法を定義 


| ネットワークの選択 | 送信元ネットワークを選択し、宛先ネットワークにマッピングします。 


| テンプレートのカスタマイズ  a| 
「既存の vCenter に登録」に vCenter クレデンシャルを入力します。Create SnapCenter Plug-in for VMware vSphere credentials * で、 SnapCenter Plug-in for VMware vSphere のクレデンシャルを入力します。


NOTE: 指定したユーザ名とパスワードをメモしておきます。SnapCenter Plug-in for VMware vSphereの設定をあとで変更する場合は、これらのクレデンシャルを使用する必要があります。

[ ネットワークプロパティの設定 *] に、ネットワーク情報を入力します。* Setup Date and Time * で、 vCenter が配置されているタイムゾーンを選択します。



| 選択内容の確認 | ページを確認して、 [ 完了 ] をクリックします。 
|===
+

NOTE: すべてのホストにIPアドレスを設定する必要があります（FQDNホスト名はサポートされません）。導入処理では、導入前に入力した内容は検証されません。

. SnapCenter Plug-in for VMware vSphere が導入されている VM に移動し、 * 概要 * タブをクリックして * 電源オン * ボックスをクリックして、 SnapCenter VMware プラグインを起動します。
. SnapCenter VMware プラグインの電源をオンにした状態で、展開された SnapCenter VMware プラグインを右クリックし、 * ゲスト OS * を選択して、 * VMware Tools のインストール * をクリックします。
+
導入が完了するまでに数分かかることがあります。SnapCenter VMwareプラグインの電源がオンになると導入が成功したことが通知され、VMware Toolsがインストールされ、SnapCenter VMwareプラグインへのログインを求める画面が表示されます。

+
SnapCenter VMwareプラグインが導入されているIPアドレスが画面に表示されます。IPアドレスをメモします。SnapCenter VMwareプラグインの設定を変更する場合は、SnapCenter VMwareプラグインの管理GUIにログインする必要があります。

. 導入画面に表示されたIPアドレスで導入ウィザードで指定したクレデンシャルを使用してSnapCenter VMwareプラグインの管理GUIにログインし、SnapCenter VMwareプラグインがvCenterに接続されて有効になっていることをダッシュボードで確認します。
+
管理GUIにアクセスするには、の形式を使用し `\https://<appliance-IP-address>:8080` ます。

+
導入時に設定したadminユーザ名とパスワード、およびメンテナンスコンソールを使用して生成されたMFAトークンを使用してログインします。

. vCenter HTML5 クライアントにログインし、ツールバーの * メニュー * をクリックして、 * SnapCenter Plug-in for VMware vSphere * を選択します

