---
sidebar: sidebar 
permalink: scpivs44_mount_a_backup.html 
keywords:  
summary: バックアップ内のファイルにアクセスする必要がある場合は、バックアップから従来のデータストアをマウントできます。バックアップは、バックアップが作成されたESXiホスト、または同じタイプのVMおよびホスト構成を使用する別のESXiホストにマウントできます。データストアはホストに複数回マウントできます。 
---
= バックアップのマウント
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
バックアップ内のファイルにアクセスする必要がある場合は、バックアップから従来のデータストアをマウントできます。バックアップは、バックアップが作成されたESXiホスト、または同じタイプのVMおよびホスト構成を使用する別のESXiホストにマウントできます。データストアはホストに複数回マウントできます。

VVOLデータストアはマウントできません。

.開始する前に
* 代替ESXiホストがストレージに接続できることを確認する
+
別の ESXi ホストにマウントする場合は、代替の ESXi ホストがストレージに接続可能で、次の条件を満たしていることを確認する必要があります。 ** 元のホストと同じ UID および GID ** 元のホストと同じバージョンの SnapCenter Plug-in for VMware vSphere 仮想アプライアンス

* ストレージイニシエータをESXiにマッピング
+
ストレージシステムのイニシエータがESXiにマッピングされていることを確認します。

* 古いLUNをクリーンアップ
+
ESXiで検出できる一意のLUNはデータストアごとに1つだけであるため、複数検出された場合は処理が失敗します。これは、前のマウント処理が完了する前にマウント処理を開始した場合、LUNを手動でクローニングした場合、またはアンマウント処理中にストレージからクローンが削除されなかった場合に発生することがあります。複数のクローンが検出されないようにするには、ストレージ上の古いLUNをすべてクリーンアップする必要があります。



.タスクの内容
データストアが配置されているFabricPoolのストレージ階層が使用できない場合、マウント処理が失敗することがあります。

.手順
. VMware vSphere Clientで、ツールバーの*メニュー*をクリックし、ドロップダウンリストから*ストレージ*を選択します。
. データストアを右クリックし、ドロップダウンリストから「 * NetApp SnapCenter * 」を選択して、セカンダリドロップダウンリストから「 * Mount Backup * 」を選択します。
. [ データストアのマウント *] ページで、バックアップとバックアップの場所 ( プライマリまたはセカンダリ ) を選択し、 [ 完了 *] をクリックします。
. オプション：データストアがマウントされたことを確認するには、次の手順を実行します。
+
.. ツールバーの * メニュー * をクリックし、ドロップダウン・リストから * ストレージ * を選択します。
.. 左側のナビゲーションペインで、マウントしたデータストアがリストの上部に表示されます。
+
SnapVaultスケジュールで保護されており、ONTAP 8.3を実行しているSnapVaultデスティネーションボリュームで接続またはマウント処理を実行すると、接続またはマウントダイアログ画面に追加のSnapshotが表示されることがあります。これは、接続処理またはマウント処理でSnapVaultデスティネーションボリュームがクローニングされ、ONTAPで新しいSnapshotを作成してボリュームが更新されるためです。

+
ボリュームのクローニング時に新しいSnapshotが作成されないようにするには、SnapVaultボリュームのONTAPスケジュールをオフにします。以前の既存のSnapshotは削除されません。




