---
sidebar: sidebar 
permalink: scpivs44_add_a_single_vm_or_datastore_to_a_resource_group.html 
keywords:  
summary: SnapCenter Plug-in for VMware vSphereで管理されている既存のリソースグループに、単一のVMまたはデータストアを簡単に追加できます。 
---
= 単一のVMまたはデータストアをリソースグループに追加する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenter Plug-in for VMware vSphereで管理されている既存のリソースグループに、単一のVMまたはデータストアを簡単に追加できます。

.タスクの内容
SANおよびNASデータストアは追加できますが、VSANまたはVVOLデータストアは追加できません。

.手順
. VMware vSphere ClientのGUIで、ツールバーの* Menu *をクリックし、追加するVMまたはデータストアに移動します。
. 左側のナビゲーションペインで、 VM またはデータストアを右クリックし、ドロップダウンリストから * NetApp SnapCenter * を選択して、セカンダリドロップダウンリストから * リソースグループに追加 * を選択します。
+
最初に、選択した VM が配置されているストレージシステムが SnapCenter で管理されているかどうかが確認され、次にリソースグループに追加 * ページが表示されます。というメッセージが表示された場合は `SnapCenter Compatibility Error` 、選択したVMがSnapCenterに対応していないため、まず適切なStorage VMをSnapCenterに追加する必要があります。

. [ リソースグループに追加 ] ページで、リソースグループを選択し、 [OK] をクリックします。
+
OK をクリックすると、 SnapCenter が管理していること、および選択した VM またはデータストアが配置されているストレージとの互換性があることが最初に確認されます。

+
というメッセージが表示された場合は `Selected <resource-name> is not SnapCenter compatible` 、選択したVMまたはデータストアがSnapCenterと互換性がありません。詳細については、を参照してください link:scpivs44_create_resource_groups_for_vms_and_datastores.html#manage-compatibility-check-failures["互換性チェックの失敗を管理"] 。


