---
sidebar: sidebar 
permalink: scpivs44_disable_and_enable_plugin.html 
keywords:  
summary: SnapCenterのデータ保護機能が不要になった場合は、SnapCenter VMwareプラグインの設定を変更する必要があります。たとえば、テスト環境にプラグインを導入した場合、SnapCenterの機能をテスト環境で無効にし、本番環境で有効にしなければならないことがあります。 
---
= SnapCenter Plug-in for VMware vSphereを無効にして有効にする
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SnapCenterのデータ保護機能が不要になった場合は、SnapCenter VMwareプラグインの設定を変更する必要があります。たとえば、テスト環境にプラグインを導入した場合、SnapCenterの機能をテスト環境で無効にし、本番環境で有効にしなければならないことがあります。

.開始する前に
* 管理者権限が必要です。
* 実行中のSnapCenterジョブがないことを確認します。


.タスクの内容
SnapCenter VMwareプラグインを無効にすると、すべてのリソースグループが中断され、プラグインがvCenterで拡張機能として登録解除されます。

SnapCenter VMwareプラグインを有効にすると、プラグインがvCenterで拡張機能として登録され、すべてのリソースグループが本番モードになり、すべてのスケジュールが有効になります。

.手順
. オプション： SnapCenter VMware プラグインの MySQL リポジトリを新しい仮想アプライアンスにリストアする場合にバックアップします。
+
link:scpivs44_back_up_the_snapcenter_plug-in_for_vmware_vsphere_mysql_database.html["SnapCenter Plug-in for VMware vSphere MySQLデータベースのバックアップ"]です。

. の形式を使用して、SnapCenter VMwareプラグインの管理GUIにログインし `\https://<OVA-IP-address>:8080`ます。導入時に設定したadminユーザ名とパスワード、およびメンテナンスコンソールを使用して生成されたMFAトークンを使用してログインします。
+
プラグインを導入すると、SnapCenter VMwareプラグインのIPが表示されます。

. 左側のナビゲーションペインで * Configuration * をクリックし、次に * Plug-in Details * セクションの Service オプションの選択を解除してプラグインを無効にします。
. 選択内容を確認します。
+
** SnapCenter VMwareプラグインのみを使用してVM整合性バックアップを実行した場合
+
プラグインは無効になっており、これ以上の操作は必要ありません。

** SnapCenter VMwareプラグインを使用してアプリケーションと整合性のあるバックアップを実行した場合
+
プラグインが無効になっているため、さらにクリーンアップが必要です。

+
... VMware vSphereにログインします。
... VMの電源をオフにします。
... 左側のナビゲーション画面で、SnapCenter VMwareプラグインのインスタンス（仮想アプライアンスの導入時に使用されたファイルの名前）を右クリックし `.ova` 、*[ディスクから削除]*を選択します。
... SnapCenterにログインし、vSphereホストを削除します。





